### ISSUE TITLE
License

### ISSUE THREAD

**Issue by noxify** [Symfoni/Synchronizer#1]
Hi,

while evaluating which is the best solution to transfer some data we found your script.
Unfortunately there is no license defined.

Is it also GPL as in your other repository or MIT?

Thanks!

**Comment by dvdamme** [comment]
Hi noxify,

This was originally an attempt at creating a GitHub account for the company I worked for, but I have renamed in now.
License file has been added.

Can I ask what you will be using the script for?

Best regards,
David

**Comment by noxify** [comment]
Hi,

thanks for adding the License.

> Can I ask what you will be using the script for?

We have currently some manual steps to transport data from ENV1 to ENV2.
Currently we have 8 tables which are exported and imported via XML.

We have to ensure that the import order is correct, that we have the correct data (some of the tables are just M2M tables), etc...

The goal was to reduce the failure rate.

While testing your script, we found some points which we have to evaluate and to decide how we can handle it (we have also some other alternatives).

1. The script works only in `global` scope
2. The API auth uses `basic` 

To 1:
In the script, you're using `gs.log` - When calling the script in a custom scope, an exception is shown.
You're using `GlideEncrypter` which is not supported in custom scopes

To 2:
We a compliance which says "API calls have to use oAuth". 

----

I hope this answers your question :)
